start
TuringAI-Team/chatgpt-discord-bot pull request #15
Opened 2023-03-09 09:37 UTC by amosayomide05

2023-03-09 19:18 UTC, MrlolDev requested changes

2023-03-09 19:18 UTC, MrlolDev commented on src/telegram/events/message.ts
> +      else if (message.commandName == "start") {
use command handler not ifs

2023-03-09 19:21 UTC, amosayomide05 commented on src/telegram/events/message.ts
> +      else if (message.commandName == "start") {
I have zero clue

2023-03-27 00:02 UTC, iosonoagenda commented
Ok

2023-04-17 04:44 UTC, closed without merging